using System;
namespace HelloWorld
{
  class Hello
  {
    Console.WriteLine("Hello World")
    int i = 1;
   / Console.WriteLine("i=OneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOneOneAndOneAndOne")   
  }
}
